title: RE Reports
description: Technical analysis, threat intelligence reports, and malware reverse engineering write-ups.
theme: jekyll-theme-hacker
permalink: /:title/

collections:
  reports:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: reports
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-titles-from-headings
